name: CI/CD - Docker Hub & Render

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: just4hoursleep/hello-docker

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          SHA_TAG=sha-${GITHUB_SHA::7}
          echo "sha_tag=$SHA_TAG" >> $GITHUB_OUTPUT
          echo "latest_tag=latest" >> $GITHUB_OUTPUT

      - name: Build & Push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.latest_tag }}
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.sha_tag }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      # ─────────────────────────────────────────────────────────────
      # Opción A (simple): Render Deploy Hook
      # ─────────────────────────────────────────────────────────────
      - name: Deploy to Render via Deploy Hook (imgURL = sha tag)
        if: ${{ success() && secrets.RENDER_DEPLOY_HOOK != '' }}
        run: |
          IMG_URL="docker.io/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.sha_tag }}"
          # Si tu hook ya trae query (?key=...), usa "&imgURL=", si no, usa "?imgURL="
          # Ajusta la siguiente línea si tu hook no tiene querystring:
          curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}&imgURL=${IMG_URL}"

      # ─────────────────────────────────────────────────────────────
      # Opción B (avanzada): Render REST API
      # ─────────────────────────────────────────────────────────────
      - name: Deploy to Render via API (imgUrl)
        if: ${{ success() && secrets.RENDER_API_KEY != '' && secrets.RENDER_SERVICE_ID != '' }}
        run: |
          IMG_URL="docker.io/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.sha_tag }}"
          curl -fsS -X POST \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"clearCache\":false, \"imageUrl\":\"${IMG_URL}\"}"
